---
name: USB-Test
version: dev
slug: usb-test
description: USB Test
url: "https://github.com/dfigus/addon-usb-test"
ingress: true
ingress_port: 0
ingress_stream: true
init: false
#usb: true
#privileged:
#  - SYS_MODULE
full_access: true
panel_icon: mdi:television
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
devices:
  - /dev/dvb/
  - /dev/dvb/adapter0/demux0
  - /dev/dvb/adapter0/dvr0
  - /dev/dvb/adapter0/frontend0
  - /dev/dvb/adapter0/net0
  - /dev/dvb/adapter1/demux0
  - /dev/dvb/adapter1/dvr0
  - /dev/dvb/adapter1/frontend0
  - /dev/dvb/adapter1/net0
  - /dev/dvb/adapter2/demux0
  - /dev/dvb/adapter2/dvr0
  - /dev/dvb/adapter2/frontend0
  - /dev/dvb/adapter2/net0
  - /dev/dvb/adapter3/demux0
  - /dev/dvb/adapter3/dvr0
  - /dev/dvb/adapter3/frontend0
  - /dev/dvb/adapter3/net0
  - /dev/dvb/adapter4/demux0
  - /dev/dvb/adapter4/dvr0
  - /dev/dvb/adapter4/frontend0
  - /dev/dvb/adapter4/net0
  - /dev/dvb/adapter5/demux0
  - /dev/dvb/adapter5/dvr0
  - /dev/dvb/adapter5/frontend0
  - /dev/dvb/adapter5/net0
  - /dev/dvb/adapter6/demux0
  - /dev/dvb/adapter6/dvr0
  - /dev/dvb/adapter6/frontend0
  - /dev/dvb/adapter6/net0
  - /dev/dvb/adapter7/demux0
  - /dev/dvb/adapter7/dvr0
  - /dev/dvb/adapter7/frontend0
  - /dev/dvb/adapter7/net0
  - /dev/dvb/adapter8/demux0
  - /dev/dvb/adapter8/dvr0
  - /dev/dvb/adapter8/frontend0
  - /dev/dvb/adapter8/net0
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vcsm-cma
  - /dev/vchiq
map:
  - addon_config:rw
  - share:rw
  - media:rw
